trigger:
  branches:
    include:
    - development
  tags:
    include:
    - v*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
    npm install --global tslint
  displayName: 'Install yarn and tslint'
  
- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo $(Agent.OS)
    # echo "Compile vscode-plugin and Run Unit Tests"
    echo ">>> Compile vscode-test and pretest"
    yarn && yarn run pretest
    echo ">>> Run Unit Tests"
    yarn && yarn run test
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'